/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 05-9月-2018 17:47:02 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `account` CASCADE
;

DROP TABLE IF EXISTS `account_change` CASCADE
;

DROP TABLE IF EXISTS `account_charge` CASCADE
;

DROP TABLE IF EXISTS `account_charge_void` CASCADE
;

DROP TABLE IF EXISTS `account_refund` CASCADE
;

DROP TABLE IF EXISTS `account_sale` CASCADE
;

DROP TABLE IF EXISTS `account_void` CASCADE
;

DROP TABLE IF EXISTS `member` CASCADE
;

DROP TABLE IF EXISTS `member_info` CASCADE
;

DROP TABLE IF EXISTS `member_source` CASCADE
;

/* Create Tables */

CREATE TABLE `account`
(
	`account_id` CHAR(64) NOT NULL COMMENT '账户ID',
	`account_no` CHAR(64) NULL COMMENT '账户号码',
	`member_id` CHAR(64) NULL COMMENT '会员ID',
	`balance` DECIMAL(12,2) NULL DEFAULT 0 COMMENT '账户余额',
	`create_time` DATETIME NULL COMMENT '创建时间',
	`update_time` DATETIME NULL COMMENT '更新时间',
	CONSTRAINT `PK_account` PRIMARY KEY (`account_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COMMENT = '账户'

;

CREATE TABLE `account_change`
(
	`account_change_id` CHAR(64) NOT NULL COMMENT '主键',
	`change_type` CHAR(1) NULL COMMENT '变动类型：0不变，1增加，2减少',
	`change_value` DECIMAL(12,2) NULL COMMENT '变化值',
	`member_id` CHAR(64) NULL COMMENT '会员ID',
	`account_id` CHAR(64) NULL COMMENT '账户ID',
	`balance` DECIMAL(12,2) NULL COMMENT '变动后余额',
	`create_time` DATETIME NULL COMMENT '添加时间',
	`update_time` DATETIME NULL COMMENT '更新时间',
	CONSTRAINT `PK_account_change` PRIMARY KEY (`account_change_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COMMENT = '账户变动记录(按用户分表)'

;

CREATE TABLE `account_charge`
(
	`account_charge_id` CHAR(64) NOT NULL COMMENT '主键',
	`change_value` DECIMAL(12,2) NULL COMMENT '变动值',
	`change_memo` VARCHAR(50) NULL COMMENT '变动原因',
	`member_id` CHAR(64) NULL COMMENT '会员ID',
	`account_id` CHAR(64) NULL COMMENT '账户ID',
	`charge_order_id` CHAR(64) NULL COMMENT '充值订单号',
	`create_time` DATETIME NULL COMMENT '添加时间',
	`update_time` DATETIME NULL COMMENT '更新时间',
	CONSTRAINT `PK_account_charge` PRIMARY KEY (`account_charge_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COMMENT = '充值记录(按用户分表)'

;

CREATE TABLE `account_charge_void`
(
	`account_charge_void_id` CHAR(64) NOT NULL COMMENT '主键',
	`change_value` DECIMAL(12,2) NULL COMMENT '变动值',
	`change_memo` VARCHAR(50) NULL COMMENT '变动原因',
	`member_id` CHAR(64) NULL COMMENT '会员ID',
	`account_id` CHAR(64) NULL COMMENT '账户ID',
	`charge_order_id` CHAR(64) NULL COMMENT '原充值订单号',
	`charge_void_order_id` CHAR(64) NULL COMMENT '充值撤销订单号',
	`create_time` DATETIME NULL COMMENT '添加时间',
	`update_time` DATETIME NULL COMMENT '更新时间',
	CONSTRAINT `PK_account_charge_void` PRIMARY KEY (`account_charge_void_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COMMENT = '充值撤销记录(按用户分表)'

;

CREATE TABLE `account_refund`
(
	`account_refund_id` CHAR(64) NOT NULL COMMENT '主键',
	`change_value` DECIMAL(12,2) NULL COMMENT '变动值',
	`change_memo` VARCHAR(50) NULL COMMENT '变动原因',
	`member_id` CHAR(64) NULL COMMENT '会员ID',
	`account_id` CHAR(64) NULL COMMENT '账户ID',
	`sale_order_id` CHAR(64) NULL COMMENT '原消费订单号',
	`refund_order_id` CHAR(64) NULL COMMENT '退款订单号',
	`create_time` DATETIME NULL COMMENT '添加时间',
	`update_time` DATETIME NULL COMMENT '更新时间',
	CONSTRAINT `PK_account_refund` PRIMARY KEY (`account_refund_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COMMENT = '退款记录(按用户分表)'

;

CREATE TABLE `account_sale`
(
	`account_sale_id` CHAR(64) NOT NULL COMMENT '主键',
	`change_value` DECIMAL(12,2) NULL COMMENT '变动值',
	`change_memo` VARCHAR(50) NULL COMMENT '变动原因',
	`member_id` CHAR(64) NULL COMMENT '会员ID',
	`account_id` CHAR(64) NULL COMMENT '账户ID',
	`sale_order_id` CHAR(64) NULL COMMENT '消费订单号',
	`create_time` DATETIME NULL COMMENT '添加时间',
	`update_time` DATETIME NULL COMMENT '更新时间',
	CONSTRAINT `PK_account_sale` PRIMARY KEY (`account_sale_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COMMENT = '消费记录(按用户分表)'

;

CREATE TABLE `account_void`
(
	`account_void_id` CHAR(64) NOT NULL COMMENT '主键',
	`change_value` DECIMAL(12,2) NULL COMMENT '变动值',
	`change_memo` VARCHAR(50) NULL COMMENT '变动原因',
	`member_id` CHAR(64) NULL COMMENT '会员ID',
	`account_id` CHAR(64) NULL COMMENT '账户ID',
	`sale_order_id` CHAR(64) NULL COMMENT '原消费订单号',
	`void_order_id` CHAR(64) NULL COMMENT '撤销订单号',
	`create_time` DATETIME NULL COMMENT '添加时间',
	`update_time` DATETIME NULL COMMENT '更新时间',
	CONSTRAINT `PK_account_void` PRIMARY KEY (`account_void_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COMMENT = '撤销记录(按用户分表)'

;

CREATE TABLE `member`
(
	`member_id` CHAR(64) NOT NULL COMMENT '会员ID',
	`member_name` VARCHAR(50) NULL,
	`sex` CHAR(1) NULL COMMENT '性别',
	`telephone` VARCHAR(50) NULL COMMENT '手机号码',
	`create_time` DATETIME NULL COMMENT '创建时间',
	`update_time` DATETIME NULL COMMENT '更新时间',
	CONSTRAINT `PK_member` PRIMARY KEY (`member_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COMMENT = '会员'

;

CREATE TABLE `member_info`
(
	`member_info_id` CHAR(64) NOT NULL COMMENT '主键',
	`member_id` CHAR(64) NULL COMMENT '会员ID',
	`info_key` VARCHAR(50) NULL COMMENT '会员信息项，如手机、地址、姓名等',
	`info_value` VARCHAR(100) NULL COMMENT '会员信息值',
	`create_time` DATETIME NULL COMMENT '创建时间',
	`update_time` DATETIME NULL COMMENT '更新时间',
	CONSTRAINT `PK_member_info` PRIMARY KEY (`member_info_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COMMENT = '会员信息'

;

CREATE TABLE `member_source`
(
	`member_source_id` CHAR(64) NOT NULL COMMENT '主键',
	`member_id` CHAR(64) NULL COMMENT '会员ID',
	`source_id` VARCHAR(100) NULL COMMENT '来源ID',
	`source` VARCHAR(50) NULL COMMENT '会员来源,WECHAT、ALIPAY、MERCHANT',
	CONSTRAINT `PK_member_source` PRIMARY KEY (`member_source_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COMMENT = '会员来源'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `account` 
 ADD INDEX `IXFK_account_member` (`member_id` ASC)
;

ALTER TABLE `account_change` 
 ADD INDEX `IXFK_account_change_account` (`account_id` ASC)
;

ALTER TABLE `account_change` 
 ADD INDEX `IXFK_account_change_member` (`member_id` ASC)
;

ALTER TABLE `account_charge` 
 ADD INDEX `IXFK_account_charge_account` (`account_id` ASC)
;

ALTER TABLE `account_charge` 
 ADD INDEX `IXFK_account_charge_member` (`member_id` ASC)
;

ALTER TABLE `account_charge_void` 
 ADD INDEX `IXFK_account_charge_void_account` (`account_id` ASC)
;

ALTER TABLE `account_charge_void` 
 ADD INDEX `IXFK_account_charge_void_member` (`member_id` ASC)
;

ALTER TABLE `account_refund` 
 ADD INDEX `IXFK_account_refund_account` (`account_id` ASC)
;

ALTER TABLE `account_refund` 
 ADD INDEX `IXFK_account_refund_member` (`member_id` ASC)
;

ALTER TABLE `account_sale` 
 ADD INDEX `IXFK_account_sale_account` (`account_id` ASC)
;

ALTER TABLE `account_sale` 
 ADD INDEX `IXFK_account_sale_member` (`member_id` ASC)
;

ALTER TABLE `account_void` 
 ADD INDEX `IXFK_account_void_account` (`account_id` ASC)
;

ALTER TABLE `account_void` 
 ADD INDEX `IXFK_account_void_member` (`member_id` ASC)
;

ALTER TABLE `member_info` 
 ADD INDEX `IXFK_member_info_member` (`member_id` ASC)
;

ALTER TABLE `member_source` 
 ADD INDEX `IXFK_member_source_member` (`member_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `account` 
 ADD CONSTRAINT `FK_account_member`
	FOREIGN KEY (`member_id`) REFERENCES `member` (`member_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `account_change` 
 ADD CONSTRAINT `FK_account_change_account`
	FOREIGN KEY (`account_id`) REFERENCES `account` (`account_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `account_change` 
 ADD CONSTRAINT `FK_account_change_member`
	FOREIGN KEY (`member_id`) REFERENCES `member` (`member_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `account_charge` 
 ADD CONSTRAINT `FK_account_charge_account`
	FOREIGN KEY (`account_id`) REFERENCES `account` (`account_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `account_charge` 
 ADD CONSTRAINT `FK_account_charge_member`
	FOREIGN KEY (`member_id`) REFERENCES `member` (`member_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `account_charge_void` 
 ADD CONSTRAINT `FK_account_charge_void_account`
	FOREIGN KEY (`account_id`) REFERENCES `account` (`account_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `account_charge_void` 
 ADD CONSTRAINT `FK_account_charge_void_member`
	FOREIGN KEY (`member_id`) REFERENCES `member` (`member_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `account_refund` 
 ADD CONSTRAINT `FK_account_refund_account`
	FOREIGN KEY (`account_id`) REFERENCES `account` (`account_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `account_refund` 
 ADD CONSTRAINT `FK_account_refund_member`
	FOREIGN KEY (`member_id`) REFERENCES `member` (`member_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `account_sale` 
 ADD CONSTRAINT `FK_account_sale_account`
	FOREIGN KEY (`account_id`) REFERENCES `account` (`account_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `account_sale` 
 ADD CONSTRAINT `FK_account_sale_member`
	FOREIGN KEY (`member_id`) REFERENCES `member` (`member_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `account_void` 
 ADD CONSTRAINT `FK_account_void_account`
	FOREIGN KEY (`account_id`) REFERENCES `account` (`account_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `account_void` 
 ADD CONSTRAINT `FK_account_void_member`
	FOREIGN KEY (`member_id`) REFERENCES `member` (`member_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `member_info` 
 ADD CONSTRAINT `FK_member_info_member`
	FOREIGN KEY (`member_id`) REFERENCES `member` (`member_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `member_source` 
 ADD CONSTRAINT `FK_member_source_member`
	FOREIGN KEY (`member_id`) REFERENCES `member` (`member_id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
